### ISSUE TITLE
无三血播报以及赛题上新播报

### ISSUE THREAD

**Issue by EZLING** [MoRan23/GZCTF-BOT-QQ#2]
如题

**Comment by MoRan23** [comment]
> 如题

需要使用/open命令开启，详细可以用/help命令查看所有命令及用法

**Comment by EZLING** [comment]
使用/open打开 并未有这些播报&nbsp;




------------------ 原始邮件 ------------------
发件人: MoRan23 ***@***.***&gt;
发送时间: 2024年9月19日 00:06
收件人: MoRan23/GZCTF-BOT-QQ ***@***.***&gt;
抄送: EZLING ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MoRan23/GZCTF-BOT-QQ] 无三血播报以及赛题上新播报 (Issue #2)





  
如题
  
需要使用/open命令开启，详细可以用/help命令查看所有命令及用法

**Comment by EZLING** [comment]
使用/open打开 并未有这些播报&nbsp;
其他功能正常




------------------ 原始邮件 ------------------
发件人: MoRan23 ***@***.***&gt;
发送时间: 2024年9月19日 00:06
收件人: MoRan23/GZCTF-BOT-QQ ***@***.***&gt;
抄送: EZLING ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MoRan23/GZCTF-BOT-QQ] 无三血播报以及赛题上新播报 (Issue #2)





  
如题
  
需要使用/open命令开启，详细可以用/help命令查看所有命令及用法

**Comment by MoRan23** [comment]
> 使用/open打开 并未有这些播报&nbsp; 其他功能正常
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MoRan23 ***@***.***&gt; 发送时间: 2024年9月19日 00:06 收件人: MoRan23/GZCTF-BOT-QQ ***@***.***&gt; 抄送: EZLING ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [MoRan23/GZCTF-BOT-QQ] 无三血播报以及赛题上新播报 (Issue #2) 如题 需要使用/open命令开启，详细可以用/help命令查看所有命令及用法 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

加我QQ1677984022
